### ISSUE TITLE
Question: Can I replace R20 and R21 with 1.1 kOmh?

### ISSUE THREAD

**Issue by Aukstkalnis** [NextThingCo/DIP-VGA-PCB#1]
As I understand these resistors are PULL-UPs. So in my understanding if I replace them with 1.1 kOmh it still should be Ok. Right? And what in BOM pdf document R20 and R21 tolerance means number 603? is it OK to be 5%?

I am asking this, because I didn't brought these resistors and if I can repleace them with 1.1 kOmh I will save time by not going to shop :)

**Comment by alleybeachelectric** [comment]
R20 and R21 are intentionally left DNP, or, Do Not Populate. No need to add them :)
