### ISSUE TITLE
Add a mechanical drawing of the PCB

### ISSUE THREAD

**Issue by shalexxo** [NextThingCo/DIP-VGA-PCB#2]
Please add a mechanical drawing of the VGA PCB. 

A drawing of overall dimensions when assembled with the CHIP would be nice as well.

The main aim is to come up with a nice 3d printed case for the assembly.

**Comment by alleybeachelectric** [comment]
@shalexxo : Sorry for the delayed reply! I have updated the repository to include a PDF of the measurements of the VGA_DIP. If there is anything missing or you are looking for something more specific, don't hesitate to contact me at scott@nextthing.co. Thanks!
